apiVersion: apps/v1
kind: Deployment
metadata:
  name: binary-calculator-webapp-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: binary-calculator-webapp
  template:
    metadata:
      labels:
        app: binary-calculator-webapp
    spec:
      containers:
        - image: us-central1-docker.pkg.dev/<your-project-id>/lab3-part1/binarycalculator
          name: binary-calculator-webapp
          ports:
            - containerPort: 8080
